version: 2

seeds:
  - name: geo_location_data
    description: "Seed data with State acronym and name, and respective latitude and longitude"
    columns:
      - name: state
        description: "State Acronym"
        data_tests:
          - unique
          - not_null
      - name: name
        description: "State name"
        data_tests:
          - not_null
      - name: lat
        description: "Latitude of the city"
        data_tests:
          - not_null
      - name: lon
        description: "Longitude of the city"
        data_tests:
          - not_null
